2018-02-26 01:59:08,755 ERROR: ValueError: Cannot assign "u'ajfkajfkadf%adajk'": "SiteUser.invite_code" must be a "InviteCode" instance.
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 30, in process_form_data
    sphinx_models.SiteUser.objects.create(**record)
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/query.py", line 397, in create
    obj = self.model(**kwargs)
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/base.py", line 537, in __init__
    setattr(self, field.name, rel_obj)
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 211, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "u'ajfkajfkadf%adajk'": "SiteUser.invite_code" must be a "InviteCode" instance.
2018-02-27 01:07:52,325 ERROR: NameError: global name 'POST' is not defined
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 20, in process_form_data
    print POST.get('first_name')
NameError: global name 'POST' is not defined
2018-02-27 01:16:07,244 ERROR: NameError: global name 'entry' is not defined
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 28, in process_form_data
    context['form_data'] = entry
NameError: global name 'entry' is not defined
2018-02-27 01:16:49,058 INFO: New signup form: {'username': None, 'first_name': None, 'last_name': None, 'invite_code': None, 'team': None, 'password': None, 'email': None}
2018-02-27 02:17:28,589 INFO: New signup form: {'username': u'', 'first_name': u'Sideshow', 'last_name': u'Bobby', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 02:26:30,097 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 02:34:54,971 INFO: New signup form: {'username': None, 'first_name': None, 'last_name': None, 'invite_code': None, 'team': None, 'password': None, 'email': None}
2018-02-27 02:44:56,521 INFO: New signup form: {'username': u'', 'first_name': u'adfadf', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 02:47:03,399 INFO: New signup form: {'username': u'', 'first_name': u'kljkljkl', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 02:47:56,629 INFO: New signup form: {'username': u'', 'first_name': u'jljklj', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 02:47:56,645 INFO: New signup form: {'username': None, 'first_name': None, 'last_name': None, 'invite_code': None, 'team': None, 'password': None, 'email': None}
2018-02-27 02:54:29,940 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'jlkjk', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 03:02:11,624 INFO: New signup form: {'username': u'', 'first_name': u'ljlkjk', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 03:02:48,887 INFO: New signup form: {'username': u'', 'first_name': u'afdasdf', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 03:07:13,187 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 03:07:17,280 INFO: New signup form: {'username': u'', 'first_name': u'afadf', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 03:36:55,145 INFO: New signup form: {'username': u'', 'first_name': u'kljklj', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 03:37:53,449 INFO: New signup form: {'username': u'', 'first_name': u'kljklj', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:32:47,687 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:33:23,493 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:33:30,182 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:35:42,949 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:39:30,160 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:40:00,558 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:44:40,266 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:46:09,217 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:47:56,344 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:48:27,678 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:50:32,185 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:50:46,772 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:59:04,082 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:59:24,213 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 04:59:49,175 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:00:43,735 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:00:55,037 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:01:31,017 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:02:02,219 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:03:26,120 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:04:16,549 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:08:12,404 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:09:16,376 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:10:24,259 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:11:38,751 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:11:58,244 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 05:12:27,304 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-27 06:51:33,310 INFO: New signup form: {'username': u'sbob', 'first_name': u'Sideshow', 'last_name': u'Bob', 'invite_code': u'e8b46ad5-45f4-4bda-990b-29206351a6ab', 'team': u'3d', 'password': u'passwork1', 'email': u'bmelse2018@gmail.com'}
2018-02-27 06:54:27,183 INFO: New signup form: {'username': u'sbob', 'first_name': u'Sideshow', 'last_name': u'Bob', 'invite_code': u'e8b46ad5-45f4-4bda-990b-29206351a6ab', 'team': u'3d', 'password': u'passwork1', 'email': u'bmelse2018@gmail.com'}
2018-02-27 06:55:36,737 INFO: New signup form: {'username': u'sbob', 'first_name': u'Sideshow', 'last_name': u'Bob', 'invite_code': u'e8b46ad5-45f4-4bda-990b-29206351a6ab', 'team': u'3d', 'password': u'passwork1', 'email': u'bmelse2018@gmail.com'}
2018-02-27 06:57:07,678 INFO: New signup form: {'username': u'sbob', 'first_name': u'Sideshow', 'last_name': u'Bob', 'invite_code_input': u'e8b46ad5-45f4-4bda-990b-29206351a6ab', 'team': u'3d', 'password': u'passwork1', 'email': u'bmelse2018@gmail.com'}
2018-02-27 06:58:51,678 INFO: New signup form: {'user__username': u'sbob', 'user__first_name': u'Sideshow', 'user__last_name': u'Bob', 'invite_code_input': u'e8b46ad5-45f4-4bda-990b-29206351a6ab', 'team': u'3d', 'user__email': u'bmelse2018@gmail.com', 'user__password': u'passwork1'}
2018-02-27 07:38:02,805 INFO: New signup form: {'username': u'sbob', 'first_name': u'Sideshow', 'last_name': u'Bob', 'invite_code_input': u'e8b46ad5-45f4-4bda-990b-29206351a6ab', 'team': u'3d', 'password': u'passwork1', 'email': u'bmelse2018@gmail.com'}
2018-02-28 01:30:00,345 INFO: New signup form: {'username': u'bobby', 'first_name': u'Sideshow', 'last_name': u'Bob', 'invite_code_input': u'e8b46ad5-45f4-4bda-990b-29206351a6ab', 'team': u'3d', 'password': u'passwork1', 'email': u'bmelse2018@gmail.com'}
2018-02-28 01:44:27,763 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code_input': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-28 01:44:51,469 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code_input': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-28 01:45:33,347 INFO: New signup form: {'username': u'bob', 'first_name': u'Bobby', 'last_name': u'Brown', 'invite_code_input': u'xyz', 'team': u'3d', 'password': u'passwork1', 'email': u'bob@burger.com'}
2018-02-28 01:45:33,535 ERROR: IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 60, in create_new_user
    invite_obj = invite_model.objects.filter(code=user_data.get('invite_code_input'))[0]
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/query.py", line 295, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
2018-02-28 01:46:27,629 INFO: New signup form: {'username': u'bob', 'first_name': u'Bobby', 'last_name': u'Brown', 'invite_code_input': u'xyz', 'team': u'3d', 'password': u'passwork1', 'email': u'bob@b.com'}
2018-02-28 01:51:52,483 INFO: New signup form: {'username': u'bob2', 'first_name': u'Bobby ', 'last_name': u'Brown', 'invite_code_input': u'xyz', 'team': u'3d', 'password': u'passwork1', 'email': u'bm@gmail.com'}
2018-02-28 01:51:52,661 ERROR: IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 60, in create_new_user
    invite_obj = invite_model.objects.filter(code=user_data.get('invite_code_input'))[0]
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/query.py", line 295, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
2018-02-28 01:51:52,665 INFO: New user added: SiteUser object
2018-02-28 05:23:39,386 INFO: New signup form: {'username': u'bob3', 'first_name': u'bobby', 'last_name': u'brown', 'invite_code_input': u'adjkafjaksdf', 'team': u'3d', 'password': u'passwork1', 'email': u'bob@gmail.com'}
2018-02-28 05:23:39,580 ERROR: IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 61, in create_new_user
    invite_obj = invite_model.objects.filter(code=user_data.get('invite_code_input'))[0]
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/query.py", line 295, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
2018-02-28 05:23:39,589 INFO: New user added: SiteUser object
2018-02-28 07:08:27,514 INFO: New signup form: {'username': u'bob4', 'first_name': u'Bobby', 'last_name': u'Brown', 'invite_code_input': u'aafk', 'team': u'3d', 'password': u'passwork1', 'email': u'bobby@gmail.com'}
2018-02-28 07:08:27,729 ERROR: IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 61, in create_new_user
    invite_obj = invite_model.objects.filter(code=user_data.get('invite_code_input'))[0]
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/query.py", line 295, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
2018-02-28 07:08:27,737 INFO: New user added: SiteUser object
2018-02-28 07:08:57,597 INFO: New signup form: {'username': u'', 'first_name': u'', 'last_name': u'', 'invite_code_input': u'', 'team': u'3d', 'password': u'', 'email': u''}
2018-02-28 20:25:57,472 INFO: New signup form: {'username': u'bob5', 'first_name': u'Bobby', 'last_name': u'Brown', 'invite_code_input': u'xyz', 'team': u'3d', 'password': u'passwork1', 'email': u'bmelse2018@gmail.com'}
2018-02-28 20:25:57,656 ERROR: IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 61, in create_new_user
    invite_obj = invite_model.objects.filter(code=user_data.get('invite_code_input'))[0]
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/query.py", line 295, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
2018-02-28 20:25:59,156 INFO: New user added: SiteUser object
2018-02-28 20:30:07,924 INFO: New signup form: {'username': u'charlie', 'first_name': u'Charlie', 'last_name': u'Chaplin', 'invite_code_input': u'xyz', 'team': u'3d', 'password': u'passwork1', 'email': u'bmelse2018@gmail.com'}
2018-02-28 20:30:08,101 ERROR: IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 61, in create_new_user
    invite_obj = invite_model.objects.filter(code=user_data.get('invite_code_input'))[0]
  File "/Users/bm/usc/perfit_docenv/lib/python2.7/site-packages/django/db/models/query.py", line 295, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
2018-02-28 20:30:09,119 INFO: New user added: SiteUser object
2018-03-02 22:19:49,059 INFO: New signup form: {'username': u'sample', 'first_name': u'sample', 'last_name': u'sample', 'invite_code_input': u'ba318605-4603-4b5f-b242-969176591dc1', 'team': u'backend', 'password': u'Foam238bald802', 'email': u'gaurav.gireesh@gmail.com'}
2018-03-02 22:19:50,947 INFO: New user added: SiteUser object
2018-03-08 21:55:00,760 ERROR: NameError: global name 'lxml' is not defined
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 146, in load_sphinx_page
    html = _parse_html(html_raw)
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 131, in _parse_html
    soup = BeautifulSoup(raw, lxml)
NameError: global name 'lxml' is not defined
2018-03-08 22:14:04,569 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_sources/genindex.html'
2018-03-08 22:15:10,221 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_sources/py-modindex.html'
2018-03-08 22:15:14,743 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/backend.html'
2018-03-08 22:15:36,482 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/backend.html'
2018-03-08 22:15:59,667 ERROR: IOError: 21
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 21] Is a directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/'
2018-03-08 22:20:46,891 ERROR: IOError: 21
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 178, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 21] Is a directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/'
2018-03-08 22:21:48,231 ERROR: IOError: 21
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 178, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 21] Is a directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/'
2018-03-08 22:22:07,703 ERROR: IOError: 21
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 178, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 21] Is a directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/'
2018-03-08 22:22:21,562 ERROR: IOError: 21
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 178, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 21] Is a directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/'
2018-03-08 22:22:44,269 ERROR: IOError: 21
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 178, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 21] Is a directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/'
2018-03-08 22:25:26,841 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 183, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/index.html'
2018-03-08 22:25:51,397 ERROR: TypeError: _parse_html() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 186, in load_sphinx_page
    html = _parse_html(html_raw)
TypeError: _parse_html() takes exactly 2 arguments (1 given)
2018-03-08 22:26:23,282 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 184, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_sources/index.rst.txt'
2018-03-08 22:27:52,456 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 184, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/search.html?q=cloth'
2018-03-08 22:28:11,704 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 184, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_sources/index.rst.txt'
2018-03-08 22:28:15,500 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 184, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_sources/index.rst.txt'
2018-03-08 22:31:53,069 ERROR: IOError: 21
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 184, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 21] Is a directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/'
2018-03-08 22:31:58,123 ERROR: IOError: 21
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 184, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 21] Is a directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/'
2018-03-08 22:36:25,518 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 172, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 22:38:19,689 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 172, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 22:41:38,323 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 172, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 22:41:45,159 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 172, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 22:50:48,267 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 22:51:00,586 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 22:51:11,897 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 22:56:10,616 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=deploy'
2018-03-08 22:59:39,692 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 22:59:44,951 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 174, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=deploy'
2018-03-08 23:11:02,945 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 23:11:35,971 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 23:12:08,544 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 23:14:07,870 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 23:14:40,395 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-08 23:14:49,945 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:16:23,205 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:16:58,358 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:18:01,602 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:18:52,580 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:20:39,963 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:21:22,077 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:39:31,651 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:39:36,066 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:39:54,455 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:40:43,549 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:42:42,613 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:42:58,566 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:43:12,435 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:43:43,430 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:43:52,712 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:44:02,325 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:44:25,741 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:44:52,073 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:44:58,502 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:45:19,735 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:45:35,241 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:45:36,916 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-08 23:49:16,117 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth'
2018-03-09 00:44:04,635 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 175, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-09 00:45:16,354 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 177, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/search.html?q=cloth&check_keywords=yes&area=default'
2018-03-09 00:51:25,836 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 181, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/backend.html?highlight=cloth'
2018-03-09 00:51:38,270 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 181, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/backend.html?highlight=cloth'
2018-03-09 00:52:30,545 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 181, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/backend.html?highlight=cloth'
2018-03-09 00:53:30,059 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 181, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/backend.html?highlight=cloth'
2018-03-09 00:53:39,525 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 181, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/backend.html?highlight=cloth%20model'
2018-03-09 00:53:42,086 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 181, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/backend.html?highlight=cloth%20model'
2018-03-09 00:56:29,094 ERROR: IOError: 2
Traceback (most recent call last):
  File "/Users/bm/usc/perfit_docenv/perfit_documentation/sphinxsite/services/helper.py", line 181, in load_sphinx_page
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: u'/Users/bm/usc/perfit_docenv/perfit_documentation/sphinx_html/_build/html/backend.html?highlight=cloth%20model'
